version: "3"

services:

  backend:
    build: ./api
    #volumes:
      #- ./api:/usr/src/api
    ports:
      - 6002:6002
    depends_on:
      - database

  database:
    image: mongo:4.0.15-xenial
    ports:
      - 27018:27017

  web:
    build: ./app
    ports:
      - 80:80
    depends_on:
      - backend

  #frontend:
    #build: ./app
    ##volumes:
      ##- ./app:/usr/src/app
    #ports:
      #- 80:3000
    #depends_on:
      #- backend

  #react_app:
    #build: ./app

  #website:
    #image: php:apache
    #volumes:
      #- ./front:/var/www/html
    #ports:
      #- 80:80

#networks:
  #default:
    ## Use a custom driver
